package com.hms.pro.domain;

// Generated Jun 19, 2016 12:53:53 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Candidate generated by hbm2java
 */
@Entity
@Table(name = "candidate", catalog = "hms")
public class Candidate implements java.io.Serializable {

	private Integer candidateId;
	private Room room;
	private String name;
	private String address;
	private String mobileNo;
	private String emergencyContactNo;
	private String occupation;
	private String workPlace;
	private String idType;
	private String idNo;
	private String photo;
	private String idProof;
	private Date joinDate;
	private Date canPaymentDate;
	private Integer candidateFee;
	private Integer dueAmount;
	private Date dueDate;
	private String paymentStatus;
	private int isActive; // 1 for active 0 for inactive
	private Date vacationDate;
	private int vacationFlag; // 1 for active 0 for incative
	private Date pendingDueDate;
	private Set<Payment> payments = new HashSet<Payment>(0);

	public Candidate() {
	}

	public Candidate(Date joinDate) {
		this.joinDate = joinDate;
	}

	public Candidate(Room room, String name, String address, String mobileNo,
			String emergencyContactNo, String occupation, String workPlace,
			String idType, String idNo, String photo, String idProof,
			Date joinDate, Date canPaymentDate, Integer candidateFee,
			Integer dueAmount, Date dueDate, String paymentStatus,
			Set<Payment> payments) {
		this.room = room;
		this.name = name;
		this.address = address;
		this.mobileNo = mobileNo;
		this.emergencyContactNo = emergencyContactNo;
		this.occupation = occupation;
		this.workPlace = workPlace;
		this.idType = idType;
		this.idNo = idNo;
		this.photo = photo;
		this.idProof = idProof;
		this.joinDate = joinDate;
		this.canPaymentDate = canPaymentDate;
		this.candidateFee = candidateFee;
		this.dueAmount = dueAmount;
		this.dueDate = dueDate;
		this.paymentStatus = paymentStatus;
		this.payments = payments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "candidate_id", unique = true, nullable = false)
	public Integer getCandidateId() {
		return this.candidateId;
	}

	public void setCandidateId(Integer candidateId) {
		this.candidateId = candidateId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "room")
	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "mobile_no", length = 45)
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "emergency_contact_no", length = 45)
	public String getEmergencyContactNo() {
		return this.emergencyContactNo;
	}

	public void setEmergencyContactNo(String emergencyContactNo) {
		this.emergencyContactNo = emergencyContactNo;
	}

	@Column(name = "occupation", length = 45)
	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	@Column(name = "work_place", length = 45)
	public String getWorkPlace() {
		return this.workPlace;
	}

	public void setWorkPlace(String workPlace) {
		this.workPlace = workPlace;
	}

	@Column(name = "id_type", length = 45)
	public String getIdType() {
		return this.idType;
	}

	public void setIdType(String idType) {
		this.idType = idType;
	}

	@Column(name = "id_no", length = 45)
	public String getIdNo() {
		return this.idNo;
	}

	public void setIdNo(String idNo) {
		this.idNo = idNo;
	}

	@Column(name = "photo", length = 200)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Column(name = "id_proof", length = 200)
	public String getIdProof() {
		return this.idProof;
	}

	public void setIdProof(String idProof) {
		this.idProof = idProof;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "join_date", nullable = false, length = 10)
	public Date getJoinDate() {
		return this.joinDate;
	}

	public void setJoinDate(Date joinDate) {
		this.joinDate = joinDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "can_payment_date", length = 10)
	public Date getCanPaymentDate() {
		return this.canPaymentDate;
	}

	public void setCanPaymentDate(Date canPaymentDate) {
		this.canPaymentDate = canPaymentDate;
	}

	@Column(name = "candidate_fee")
	public Integer getCandidateFee() {
		return this.candidateFee;
	}

	public void setCandidateFee(Integer candidateFee) {
		this.candidateFee = candidateFee;
	}

	@Column(name = "due_amount")
	public Integer getDueAmount() {
		return this.dueAmount;
	}

	public void setDueAmount(Integer dueAmount) {
		this.dueAmount = dueAmount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "due_date", length = 10)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	@Column(name = "payment_status", length = 45)
	public String getPaymentStatus() {
		return this.paymentStatus;
	}

	public void setPaymentStatus(String paymentStatus) {
		this.paymentStatus = paymentStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "candidate")
	public Set<Payment> getPayments() {
		return this.payments;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}

	public int getIsActive() {
		return isActive;
	}

	public void setIsActive(int isActive) {
		this.isActive = isActive;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "vacation_date", length = 10)
	public Date getVacationDate() {
		return vacationDate;
	}

	public void setVacationDate(Date vacationDate) {
		this.vacationDate = vacationDate;
	}

	@Column(name="vacation_flag")
	public int getVacationFlag() {
		return vacationFlag;
	}

	public void setVacationFlag(int vacationFlag) {
		this.vacationFlag = vacationFlag;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pending_due_date", length = 10)
	public Date getPendingDueDate() {
		return pendingDueDate;
	}

	public void setPendingDueDate(Date pendingDueDate) {
		this.pendingDueDate = pendingDueDate;
	}
	
	

}
