package com.hms.pro.domain;

// Generated Jun 19, 2016 12:53:53 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Floor generated by hbm2java
 */
@Entity
@Table(name = "floor", catalog = "hms")
public class Floor implements java.io.Serializable {

	private Integer floorId;
	private Building building;
	private String floorName;
	private Set<Room> rooms = new HashSet<Room>(0);
	private Integer isActive;

	public Floor() {
	}

	public Floor(Building building) {
		this.building = building;
	}

	public Floor(Building building, String floorName, Set<Room> rooms) {
		this.building = building;
		this.floorName = floorName;
		this.rooms = rooms;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "floor_id", unique = true, nullable = false)
	public Integer getFloorId() {
		return this.floorId;
	}

	public void setFloorId(Integer floorId) {
		this.floorId = floorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "building", nullable = false)
	public Building getBuilding() {
		return this.building;
	}

	public void setBuilding(Building building) {
		this.building = building;
	}

	@Column(name = "floor_name", length = 45)
	public String getFloorName() {
		return this.floorName;
	}

	public void setFloorName(String floorName) {
		this.floorName = floorName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "floor")
	public Set<Room> getRooms() {
		return this.rooms;
	}

	public void setRooms(Set<Room> rooms) {
		this.rooms = rooms;
	}

	@Column(name = "isActive")
	public Integer getIsActive() {
		return isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	
}
