package com.hms.pro.domain;

// Generated Jun 19, 2016 12:53:53 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hostal generated by hbm2java
 */
@Entity
@Table(name = "hostal", catalog = "hms")
public class Hostal implements java.io.Serializable {

	private int registrationId;
	private String hostalName;
	private Date createdOn;
	private String ownerName;
	private String contactNo;
	private String mobile;
	private String address;
	private Set<Building> buildings = new HashSet<Building>(0);

	public Hostal() {
	}

	public Hostal(int registrationId) {
		this.registrationId = registrationId;
	}

	public Hostal(int registrationId, String hostalName, Date createdOn,
			String ownerName, String contactNo, String mobile, String address,
			Set<Building> buildings) {
		this.registrationId = registrationId;
		this.hostalName = hostalName;
		this.createdOn = createdOn;
		this.ownerName = ownerName;
		this.contactNo = contactNo;
		this.mobile = mobile;
		this.address = address;
		this.buildings = buildings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "registration_id", unique = true, nullable = false)
	public int getRegistrationId() {
		return this.registrationId;
	}

	public void setRegistrationId(int registrationId) {
		this.registrationId = registrationId;
	}

	@Column(name = "hostal_name", length = 60)
	public String getHostalName() {
		return this.hostalName;
	}

	public void setHostalName(String hostalName) {
		this.hostalName = hostalName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdOn", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "owner_name", length = 90)
	public String getOwnerName() {
		return this.ownerName;
	}

	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}

	@Column(name = "contact_no", length = 45)
	public String getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(String contactNo) {
		this.contactNo = contactNo;
	}

	@Column(name = "mobile", length = 45)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "address", length = 150)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hostal")
	public Set<Building> getBuildings() {
		return this.buildings;
	}

	public void setBuildings(Set<Building> buildings) {
		this.buildings = buildings;
	}

}
