package com.hms.pro.domain;

// Generated Jun 19, 2016 12:53:53 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name = "payment", catalog = "hms")
public class Payment implements java.io.Serializable {

	private int paymentId;
	private Candidate candidate;
	private Integer paidAmount;
	private Date paidDate;

	public Payment() {
	}

	public Payment(int paymentId) {
		this.paymentId = paymentId;
	}

	public Payment(int paymentId, Candidate candidate, Integer paidAmount,
			Date paidDate) {
		this.paymentId = paymentId;
		this.candidate = candidate;
		this.paidAmount = paidAmount;
		this.paidDate = paidDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "payment_id", unique = true, nullable = false)
	public int getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(int paymentId) {
		this.paymentId = paymentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "candidate")
	public Candidate getCandidate() {
		return this.candidate;
	}

	public void setCandidate(Candidate candidate) {
		this.candidate = candidate;
	}

	@Column(name = "paid_amount")
	public Integer getPaidAmount() {
		return this.paidAmount;
	}

	public void setPaidAmount(Integer paidAmount) {
		this.paidAmount = paidAmount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "paid_date", length = 10)
	public Date getPaidDate() {
		return this.paidDate;
	}

	public void setPaidDate(Date paidDate) {
		this.paidDate = paidDate;
	}

}
