package com.hms.pro.domain;

// Generated Jun 19, 2016 12:53:53 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Room generated by hbm2java
 */
@Entity
@Table(name = "room", catalog = "hms")
public class Room implements java.io.Serializable {

	private int roomId;
	private RoomType roomType;
	private Floor floor;
	private Building building;
	private String roomName;
	private Set<Candidate> candidates = new HashSet<Candidate>(0);
	private Integer isActive;
	
	public Room() {
	}

	public Room(int roomId) {
		this.roomId = roomId;
	}

	public Room(int roomId, RoomType roomType, Floor floor, String roomName,
			Set<Candidate> candidates) {
		this.roomId = roomId;
		this.roomType = roomType;
		this.floor = floor;
		this.roomName = roomName;
		this.candidates = candidates;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "room_id", unique = true, nullable = false)
	public int getRoomId() {
		return this.roomId;
	}

	public void setRoomId(int roomId) {
		this.roomId = roomId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "room_type")
	public RoomType getRoomType() {
		return this.roomType;
	}

	public void setRoomType(RoomType roomType) {
		this.roomType = roomType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "floor")
	public Floor getFloor() {
		return this.floor;
	}

	public void setFloor(Floor floor) {
		this.floor = floor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "building")
	public Building getBuilding() {
		return building;
	}

	public void setBuilding(Building building) {
		this.building = building;
	}
	
	@Column(name = "room_name", length = 45)
	public String getRoomName() {
		return this.roomName;
	}

	public void setRoomName(String roomName) {
		this.roomName = roomName;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "room")
	public Set<Candidate> getCandidates() {
		return this.candidates;
	}

	public void setCandidates(Set<Candidate> candidates) {
		this.candidates = candidates;
	}

	@Column(name = "isActive")
	public Integer getIsActive() {
		return isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}
	
	

}
